### ISSUE TITLE
[REQ] \e\ build

### ISSUE THREAD

**Issue by MarcoRavich** [nasreirma/android_device_Infinix_X556#1]
Hi there,
even if we know that it's an old device, it would be great to have an [\e\ (aka deGoogled-Lineage)](https://e.foundation/) for Hot 4 Pro (and not only) too.

We opened a 3ad @ [\e\ community](https://community.e.foundation/) were we also linked your repos:

https://community.e.foundation/t/infinix-hot-4-pro-x556-mt6737/43286

Hope can "inspire" you.

Thanks in advance.

**Comment by nasreirma** [comment]
Hey ,
I'deed it is a bit old and sadly i don't have the device atm but i did
actually started developping lineage os based on android 8 and it did boots
witha few bugs
But yeah you can found everything on my git
Good luck
Best regards

IRHMAR Nasrellah
Élève ingénieur en génie électromécanique
Ecole Nationale Supérieure d'Arts et Métiers (ENSAM)- Casablanca
Université Hassan II - Mohammedia
Casablanca
Maroc
GSM : 06 21 25 60 75

**Comment by MarcoRavich** [comment]
Thanks a lot for your quick reply.

We hope more and more cool devs like you will join the \e\ distro (which is LOS-based) too.

Here's a couple of interesting guides that may help to build it:
https://doc.e.foundation/support-topics/build-e
https://community.e.foundation/t/howto-building-e-roms-a-beginners-guide/26371

Last but not least, if you like and you have time, we invite you to join \e\ community:
https://community.e.foundation/

Thanks again,
Marco Ravich
FORART fe
Italy
